version: "3.9"
services:
  nfspoc:
    image: "${COMPOSE_PROJECT_NAME}"
    environment:
      - POC_ORDS_ENDPOINT=${POC_ORDS_ENDPOINT}
      - POC_ORDS_USERNAME=${POC_ORDS_USERNAME}
      - POC_ORDS_PASSWORD=${POC_ORDS_PASSWORD}
      - POC_ORDS_APP_ID=${POC_ORDS_APP_ID}
      - POC_ORDS_APP_PWD=${POC_ORDS_APP_PWD}
      - POC_ORDS_TICKET_LIFETIME=${POC_ORDS_TICKET_LIFETIME}
      - POC_WRAPPER_BASEPATH=${POC_WRAPPER_BASEPATH}
      - POC_APP_BASEPATH=${POC_APP_BASEPATH}
    ports:
      - "${NFCPOC_EXPOSE_PORT}:${NFCPOC_PORT}"